apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoescalado
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: midespliegue
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
